### ISSUE TITLE
Commands still works when DM'ing the bot

### ISSUE THREAD

**Issue by MGPlayzYT** [Assfugil/nickchanbot#5]
When you open a DM for the bot, typing any command will still work. Instead, it should sent a message saying "Bot commands aren't available via DM"

**Comment by Assfugil** [comment]
Why ban people from using commands in DM?

**Comment by Assfugil** [comment]
Currently, server-only commands will be filtered before trying to execute it.
like /config
it will produce a custom error `NickChanBotError`.

**Comment by MGPlayzYT** [comment]
Because that doesn't make sense

**Comment by MGPlayzYT** [comment]
Other bots doesn't have this feature

**Comment by Assfugil** [comment]
UnbelievaBoat

**Comment by MGPlayzYT** [comment]
Yeah

**Comment by MGPlayzYT** [comment]
> What about UnbelievaBoat
> It reply to dm messages

I tried it, it didn't respond.

**Comment by MGPlayzYT** [comment]
Oops

**Comment by Assfugil** [comment]
Umm default prefix is !

**Comment by Assfugil** [comment]
`!ping`

**Comment by MGPlayzYT** [comment]
> `!ping`

Oh. Apart from Unbelivaboat, some bots still doesn't have this feature.

**Comment by Assfugil** [comment]
ik but some bots does like Nick Chan#5213 and FAV bot

**Comment by Assfugil** [comment]
This can be closed

**Comment by MGPlayzYT** [comment]
Ok then.
