### ISSUE TITLE
The "/purge" command deletes Pinned Messages.

### ISSUE THREAD

**Issue by MGPlayzYT** [Assfugil/nickchanbot#8]
The bot deletes pinned messages when using the "/purge" command. Other bots like UnbelievaBoat don't delete pinned messages.

**Comment by Assfugil** [comment]
https://discord.js.org/#/docs/main/stable/class/TextChannel?scrollTo=bulkDelete

**Comment by Assfugil** [comment]
https://discord.js.org/#/docs/main/stable/class/TextChannel?scrollTo=fetchMessages
ok that means that i will have to search through the messages one by one.

**Comment by Assfugil** [comment]
the new code doesn’t work.

**Comment by Assfugil** [comment]
btw the GitHub code is not updated.
Its the stable version.

**Comment by MGPlayzYT** [comment]
Ok

**Comment by Assfugil** [comment]
DEV branch bot.js line 1083 is the new purge command
(It doesn’t work)

**Comment by Assfugil** [comment]
fixed
